# Generated by Django 4.1.1 on 2022-09-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=80)),
                ('numberOfDoor', models.IntegerField()),
                ('registration', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
